### ISSUE TITLE
Tag details file for Docker images

### ISSUE THREAD

**Issue by olemis** [skycoin/repo-info#12]
Include tag details in a format similar to Docker library metadata (e.g. [`bash tag details`](https://github.com/docker-library/repo-info/blob/master/repos/bash/tag-details.md) ).

Requires a resolution for simelo/repo-info-tools#2 .

**Comment by stdevPavelmc** [comment]
Hi, simelo/repo-info-tools#2 is solved now, but to generate the tag details files we need some extra mods that will follow.

**Comment by stdevPavelmc** [comment]
@olemis I have included the tag listing and all the info on that listed images, but need to coordinate a issue, there are some images that belongs to simelo see [here](https://github.com/simelo/skycoin-repo-info/tree/develop/repos/dev-vscode/remote/) for example.

There is a feature image from yuniers, that must be moved to skycoin repo con docker hub? or cleared the feature branch by yuniers?

Please review that and comment on the changes prior to PR.

**Comment by olemis** [comment]
Feel free to create PR any time . I do not think this is on the right track . Have you merged recent changes in `master` ? Besides , there are no such tags in `skycoin/skycoindev-vscode` repository . I ran the first build now , so there's chance for `develop` and `dind` to be there by tomorrow .

**Comment by stdevPavelmc** [comment]
I realized a few errors, fixed by now: 

- Names fixed for the folders inside `repos` (My BAD)
- Updated the list of images to process, had `simelo/skycoindev-vscode` instead of `simelo/skycoindev-vscode` from Yuniers's tests, that's why the confusion.
- Short count of tags: bug spotted, docker v2 api gives the list in pages, v1 api gives it in full, need to work it out in v2 and deal with a token to avoid pagination... wip.
- Yes changes are merged to master at simelo, and BTW I can't rise a issue on `simelo/skycoin-repo-info` why?

**Comment by olemis** [comment]
@stdevPavelmc issues must be created in `skycoin/repo-info`
